# ML hands-on exercise

Classefication with the tips dataset

In [1]:
from sklearn.svm import SVC, SVR

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.model_selection import GridSearchCV

In [4]:
import seaborn as sns

In [23]:
import pandas as pd
import numpy as np

In [5]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic',
 'anagrams',
 'anagrams',
 'anscombe',
 'anscombe',
 'attention',
 'attention',
 'brain_networks',
 'brain_networks',
 'car_crashes',
 'car_crashes',
 'diamonds',
 'diamonds',
 'dots',
 'dots',
 'dowjones',
 'dowjones',
 'exercise',
 'exercise',
 'flights',
 'flights',
 'fmri',
 'fmri',
 'geyser',
 'geyser',
 'glue',
 'glue',
 'healthexp',
 'healthexp',
 'iris',
 'iris',
 'mpg',
 'mpg',
 'penguins',
 'penguins',
 'planets',
 'planets',
 'seaice',
 'seaice',
 'taxis',
 'taxis',
 'tips',
 'tips',
 'titanic',
 'titanic',
 'anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [7]:
titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [8]:
mpg = sns.load_dataset('mpg')
mpg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [6]:
tips = sns.load_dataset('tips')

In [7]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:
y = tips.pop('smoker')
y

0       No
1       No
2       No
3       No
4       No
      ...
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, object): ['Yes', 'No']

In [10]:
X = tips
X

     total_bill   tip     sex   day    time  size
0         16.99  1.01  Female   Sun  Dinner     2
1         10.34  1.66    Male   Sun  Dinner     3
2         21.01  3.50    Male   Sun  Dinner     3
3         23.68  3.31    Male   Sun  Dinner     2
4         24.59  3.61  Female   Sun  Dinner     4
..          ...   ...     ...   ...     ...   ...
239       29.03  5.92    Male   Sat  Dinner     3
240       27.18  2.00  Female   Sat  Dinner     2
241       22.67  2.00    Male   Sat  Dinner     2
242       17.82  1.75    Male   Sat  Dinner     2
243       18.78  3.00  Female  Thur  Dinner     2

[244 rows x 6 columns]

In [14]:
tips.isna().sum()

total_bill    0
tip           0
sex           0
day           0
time          0
size          0
dtype: int64

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
clf = KNeighborsClassifier()

In [15]:
ypred = clf.fit(X,y)

ValueError: could not convert string to float: 'Female'

In [16]:
X = pd.get_dummies(X)
X

,total_bill,tip,size,sex_Male,sex_Female,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16.99,1.01,2,False,True,False,False,False,True,False,True
1,10.34,1.66,3,True,False,False,False,False,True,False,True
2,21.01,3.50,3,True,False,False,False,False,True,False,True
3,23.68,3.31,2,True,False,False,False,False,True,False,True
4,24.59,3.61,4,False,True,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,True,False,False,False,True,False,False,True
240,27.18,2.00,2,False,True,False,False,True,False,False,True
241,22.67,2.00,2,True,False,False,False,True,False,False,True
242,17.82,1.75,2,True,False,False,False,True,False,False,True
243,18.78,3.00,2,False,True,True,False,False,False,False,True

In [17]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2)

In [14]:
len(Xtrain)

195

In [15]:
len(Xtest)

49

In [18]:
clf.fit(Xtrain, ytrain)

KNeighborsClassifier()

In [19]:
ypred = clf.predict(Xtest)

In [20]:
clf.score(Xtest, ytest)

0.6326530612244898

In [21]:
ypred

array(['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No',
       'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No'], dtype=object)

In [26]:
np.array(ytest)

array(['No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No',
       'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No'],
      dtype=object)

In [30]:
Xtest.iloc[3]

total_bill      16.4
tip              2.5
size               2
sex_Male       False
sex_Female      True
day_Thur        True
day_Fri        False
day_Sat        False
day_Sun        False
time_Lunch      True
time_Dinner    False
Name: 203, dtype: object

In [24]:
import numpy as np

In [ ]:
param_grid = {
    'C': [1, 100, 1000, 10000],
    'tol': np.arange(0.001, 0.1, 0.005)
}

In [ ]:
gs = GridSearchCV()

In [25]:
np.arange(0.001, 0.1, 0.005)

array([0.001, 0.006, 0.011, 0.016, 0.021, 0.026, 0.031, 0.036, 0.041,
       0.046, 0.051, 0.056, 0.061, 0.066, 0.071, 0.076, 0.081, 0.086,
       0.091, 0.096])